### ISSUE TITLE
[Feature] add a hover tooltip for the graph

### ISSUE THREAD

**Issue by sainak** [tushar-upadhyay/Flutter_college_app#2]
a hover tooltip for the attendance graph to show the attendance and date at the point of hover would make the graph more interactive.

**Comment by tushar-upadhyay** [comment]
Hey @aakash37 
That's definitely a nice feature request but as you can see the attendance data is updated daily.. I mean a semester is of min 2-3 months 
Let's assume total our total classes held for 120  days.. As you know our mobile width is not enough to get responses to all of the dates... 
But We can surely do that month wise or week wise 
@aakash37 what are your views on this?

**Comment by sainak** [comment]
https://help.syncfusion.com/flutter/chart/tooltip
you can specify a range for which the graph can be displayed like the data monitor in android phones
I think intervals of 2-3 weeks will be fine

or make the graph scrollable

**Comment by sainak** [comment]
https://pub.dev/packages/syncfusion_flutter_charts
check out the user interaction section in this page

**Comment by tushar-upadhyay** [comment]
Great 
Can you do that? 
Open a pull request

**Comment by tushar-upadhyay** [comment]
I have many projects right now.. I you can do this, do it. 
Otherwise may be later I will implement this

**Comment by sainak** [comment]
i dont know dart I'm more of a python guy 
but here is a chart with quiet a close resemblance to what i wanted to say
https://flutter.syncfusion.com > editors > range selectors

this is the source code
https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/slider/range_selector/range_selector_with_zooming.dart

**Comment by tushar-upadhyay** [comment]
Done in the latest release
